name: Markdown lint

on: [push]

jobs:
  build:
    name: Markdown lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.json"
          #ignore_files: "examples/ignore/*"
          #rules: "examples/rules/custom.js"
